#Requires -Version 5.1
<#
.SYNOPSIS
  Builds LINE funnel workbook from funnel_raw.csv (Excel COM) and regenerates funnel_chart_data.js for funnel_three_flows.html.
#>
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$csvPath = Join-Path $root 'funnel_raw.csv'
$outPath = Join-Path $root 'LINE_funnel_dashboard.xlsx'

function SheetNameRaw { -join [char[]](0x751F, 0x30C7, 0x30FC, 0x30BF) }
function SheetNameDash { -join [char[]](0x30C0, 0x30C3, 0x30B7, 0x30E5) }

$rows = @(Import-Csv -LiteralPath $csvPath | Where-Object { $_.month -and $_.item })
$totalLabel = 'TOTAL'
$M1 = -join @([char]0x0031, [char]0x6708)
$M2 = -join @([char]0x0032, [char]0x6708)
$M3 = -join @([char]0x0033, [char]0x6708)

function MonthLabel([int]$m) {
  if ($m -eq 1) { return $M1 }
  if ($m -eq 2) { return $M2 }
  if ($m -eq 3) { return $M3 }
  return ([string]$m) + [char]0x6708
}

$matN = [System.Collections.ArrayList]@()
$matE = [System.Collections.ArrayList]@()
$matR = [System.Collections.ArrayList]@()
$monLbl = [System.Collections.ArrayList]@()
$bufN = [System.Collections.ArrayList]@()
$bufE = [System.Collections.ArrayList]@()
$bufR = [System.Collections.ArrayList]@()
foreach ($rec in $rows) {
  if ($rec.item -eq $totalLabel) {
    if ($bufN.Count -gt 0) {
      [void]$matN.Add(@($bufN.ToArray()))
      [void]$matE.Add(@($bufE.ToArray()))
      [void]$matR.Add(@($bufR.ToArray()))
      [void]$monLbl.Add((MonthLabel ([int]$rec.month)))
    }
    $bufN.Clear(); $bufE.Clear(); $bufR.Clear()
    continue
  }
  [void]$bufN.Add([double]$rec.normal_line)
  [void]$bufE.Add([double]$rec.event_line)
  [void]$bufR.Add([double]$rec.reservations)
}

function JsonMatrix([System.Collections.IEnumerable]$mat) {
  $outer = @()
  foreach ($r in $mat) {
    $inner = ($r | ForEach-Object { [string][int]$_ }) -join ','
    $outer += "[$inner]"
  }
  return '[' + ($outer -join ',') + ']'
}

$labelsJson = ($monLbl | ForEach-Object {
  $s = $_ -replace '\\', '\\\\' -replace '"', '\"'
  "`"$s`""
}) -join ','
$jsPath = Join-Path $root 'funnel_chart_data.js'
$jsBody = @"
// Auto-generated by build_dashboard.ps1 from funnel_raw.csv. Do not edit by hand.
window.FUNNEL_DATA = {
  labels: [$labelsJson],
  sources: ["Instagram","YouTube","stand.fm","note"],
  colors: ["#E91E63","#FF9800","#4CAF50","#2196F3"],
  normalLine: $(JsonMatrix $matN),
  eventLine: $(JsonMatrix $matE),
  meetings: $(JsonMatrix $matR)
};
"@
[System.IO.File]::WriteAllText($jsPath, $jsBody, [System.Text.UTF8Encoding]::new($false))

$xl = New-Object -ComObject Excel.Application
$xl.Visible = $false
$xl.DisplayAlerts = $false
$wb = $xl.Workbooks.Add()

while ($wb.Worksheets.Count -gt 1) { $wb.Worksheets.Item($wb.Worksheets.Count).Delete() }
$wsRaw = $wb.Worksheets.Item(1)
$wsRaw.Name = SheetNameRaw
$wsDash = $wb.Worksheets.Add([Type]::Missing, $wsRaw)
$wsDash.Name = SheetNameDash

$hMonth = (-join [char[]](0x5B9F, 0x65BD, 0x6708))
$hItem = (-join [char[]](0x9805, 0x76EE))
$hNorm = (-join [char[]](0x307D, 0x3093, 0x901A, 0x5E38, 0x004C, 0x0049, 0x004E, 0x0028, 0x4EBA, 0x0029))
$hEvt = (-join [char[]](0x307D, 0x3093, 0x30A4, 0x30D9, 0x30F3, 0x30C8, 0x004C, 0x0049, 0x004E, 0x0028, 0x4EBA, 0x0029))
$hRes = (-join [char[]](0x9762, 0x8AC7, 0x4E88, 0x7D04, 0x6570))
$hDrop = (-join [char[]](0x96E2, 0x8131, 0x6570, 0x0028, 0x4EBA, 0x0029))
$hLineR = (-join [char[]](0x004c, 0x0049, 0x004e, 0x79fb, 0x884c, 0x7387, 0x0028, 0x0025, 0x0029))
$hMeetR = (-join [char[]](0x9762, 0x8AC7, 0x79FB, 0x884C, 0x7387, 0x0028, 0x0025, 0x0029))
$hNormC = (-join [char[]](0x307D, 0x3093, 0x901A, 0x5E38, 0x004C, 0x0049, 0x004E, 0x69CB, 0x6210, 0x6BD4, 0x0028, 0x0025, 0x0029))
$hEvtC = (-join [char[]](0x307D, 0x3093, 0x30A4, 0x30D9, 0x30F3, 0x30C8, 0x004C, 0x0049, 0x004E, 0x69CB, 0x6210, 0x6BD4, 0x0028, 0x0025, 0x0029))

$wsRaw.Cells.Item(1, 1).Value2 = $hMonth
$wsRaw.Cells.Item(1, 2).Value2 = $hItem
$wsRaw.Cells.Item(1, 3).Value2 = $hNorm
$wsRaw.Cells.Item(1, 4).Value2 = $hEvt
$wsRaw.Cells.Item(1, 5).Value2 = $hRes
$wsRaw.Cells.Item(1, 6).Value2 = $hDrop
$wsRaw.Cells.Item(1, 7).Value2 = $hLineR
$wsRaw.Cells.Item(1, 8).Value2 = $hMeetR
$wsRaw.Cells.Item(1, 9).Value2 = $hNormC
$wsRaw.Cells.Item(1, 10).Value2 = $hEvtC
$hdr = $wsRaw.Range('A1', 'J1')
$hdr.Font.Bold = $true
$hdr.Interior.Color = 0x656565
$hdr.Font.Color = 0xFFFFFF

$row = 2
foreach ($rec in $rows) {
  $mo = [int]$rec.month
  $wsRaw.Cells.Item($row, 1).Value2 = MonthLabel $mo
  $wsRaw.Cells.Item($row, 2).Value2 = $rec.item
  $isTotal = ($rec.item -eq $totalLabel)
  if ($isTotal) {
    $start = $row - 4
    $wsRaw.Cells.Item($row, 3).Formula = "=SUM(C$($start):C$($row-1))"
    $wsRaw.Cells.Item($row, 4).Formula = "=SUM(D$($start):D$($row-1))"
    $wsRaw.Cells.Item($row, 5).Formula = "=SUM(E$($start):E$($row-1))"
  } else {
    $wsRaw.Cells.Item($row, 3).Value2 = [double]$rec.normal_line
    $wsRaw.Cells.Item($row, 4).Value2 = [double]$rec.event_line
    $wsRaw.Cells.Item($row, 5).Value2 = [double]$rec.reservations
  }
  $wsRaw.Cells.Item($row, 6).Formula = "=C$row-D$row"
  $wsRaw.Cells.Item($row, 7).Formula = "=IF(C$row>0,D$row/C$row,0)"
  $wsRaw.Cells.Item($row, 8).Formula = "=IF(D$row>0,E$row/D$row,0)"
  if ($isTotal) {
    $wsRaw.Cells.Item($row, 9).Formula = "=IF(C$row>0,1,0)"
    $wsRaw.Cells.Item($row, 10).Formula = "=IF(D$row>0,1,0)"
  } else {
    $totRow = if ($mo -eq 1) { 6 } elseif ($mo -eq 2) { 11 } else { 16 }
    $wsRaw.Cells.Item($row, 9).Formula = "=IF(C$totRow>0,C$row/C$totRow,0)"
    $wsRaw.Cells.Item($row, 10).Formula = "=IF(D$totRow>0,D$row/D$totRow,0)"
  }
  $row++
}

$wsRaw.Range('A:J').EntireColumn.AutoFit() | Out-Null
$wsRaw.Range('G:J').NumberFormat = '0.00%'
$wsRaw.Range('C:F').NumberFormat = '0'

$kpiText = (-join [char[]](
  0x4E3B, 0x8EF8, 0x004B, 0x0050, 0x0049, 0x003A, 0x0020,
  0x6708, 0x6B21, 0x306E, 0x6BB5, 0x968E, 0x5225, 0x4EBA, 0x6570, 0x3067, 0x30DC, 0x30C8, 0x30EB, 0x30CD, 0x30C3, 0x30AF, 0xFF08,
  0x901A, 0x5E38, 0x004C, 0x0049, 0x004E, 0x2192, 0x30A4, 0x30D9, 0x30F3, 0x30C8, 0x004C, 0x0049, 0x004E, 0x2192, 0x9762, 0x8AC7, 0x4E88, 0x7D04,
  0xFF09, 0x3092, 0x6700, 0x512A, 0x5148, 0x3067, 0x78BA, 0x8A8D, 0x3059, 0x308B
))
$wsDash.Range('A1', 'G1').Merge() | Out-Null
$wsDash.Cells.Item(1, 1).Value2 = $kpiText
$wsDash.Cells.Item(1, 1).WrapText = $true
$wsDash.Rows.Item(1).RowHeight = 42

$sumRows = @{ $M1 = 6; $M2 = 11; $M3 = 16 }
$dashHeaderRow = 3
$dhMonth = (-join [char[]](0x6708))
$dhNorm = (-join [char[]](0x901A, 0x5E38, 0x004C, 0x0049, 0x004E))
$dhEvt = (-join [char[]](0x30A4, 0x30D9, 0x30F3, 0x30C8, 0x004C, 0x0049, 0x004E))
$dhRes = (-join [char[]](0x9762, 0x8AC7, 0x4E88, 0x7D04))
$dhLineR = (-join [char[]](0x004c, 0x0049, 0x004e, 0x79fb, 0x884c, 0x7387))
$dhMeetR = (-join [char[]](0x9762, 0x8AC7, 0x79FB, 0x884C, 0x7387))
$dhDenom = (-join [char[]](0x9762, 0x8AC7, 0x0043, 0x0056, 0x0052, 0x6BCD, 0x6570, 0x0028, 0x30A4, 0x30D9, 0x30F3, 0x30C8, 0x004C, 0x0049, 0x004E, 0x4EBA, 0x6570, 0x0029))

$wsDash.Cells.Item($dashHeaderRow, 1).Value2 = $dhMonth
$wsDash.Cells.Item($dashHeaderRow, 2).Value2 = $dhNorm
$wsDash.Cells.Item($dashHeaderRow, 3).Value2 = $dhEvt
$wsDash.Cells.Item($dashHeaderRow, 4).Value2 = $dhRes
$wsDash.Cells.Item($dashHeaderRow, 5).Value2 = $dhLineR
$wsDash.Cells.Item($dashHeaderRow, 6).Value2 = $dhMeetR
$wsDash.Cells.Item($dashHeaderRow, 7).Value2 = $dhDenom
$wsDash.Range("A$dashHeaderRow", "G$dashHeaderRow").Font.Bold = $true

$m = 0
foreach ($label in @($M1, $M2, $M3)) {
  $m++
  $sr = $sumRows[$label]
  $dr = $dashHeaderRow + $m
  $wsDash.Cells.Item($dr, 1).Value2 = $label
  $rn = SheetNameRaw
  $wsDash.Cells.Item($dr, 2).Formula = "='$rn'!C$sr"
  $wsDash.Cells.Item($dr, 3).Formula = "='$rn'!D$sr"
  $wsDash.Cells.Item($dr, 4).Formula = "='$rn'!E$sr"
  $wsDash.Cells.Item($dr, 5).Formula = "='$rn'!G$sr"
  $wsDash.Cells.Item($dr, 6).Formula = "='$rn'!H$sr"
  $wsDash.Cells.Item($dr, 7).Formula = "='$rn'!D$sr"
}

$wsDash.Range("E$($dashHeaderRow + 1):F$($dashHeaderRow + 3)").NumberFormat = '0.00%'
$wsDash.Range("B$($dashHeaderRow + 1):D$($dashHeaderRow + 3)").NumberFormat = '0'
$wsDash.Range("G$($dashHeaderRow + 1):G$($dashHeaderRow + 3)").NumberFormat = '0"人"'

$stackTop = 10
$stackTitle = (-join [char[]](
  0x5A92, 0x4F53, 0x5225, 0xFF08, 0x5408, 0x8A08, 0x884C, 0x306A, 0x3057, 0xFF09, 0x2014, 0x0020,
  0x901A, 0x5E38, 0x004C, 0x0049, 0x004E, 0x30FB, 0x30A4, 0x30D9, 0x30F3, 0x30C8, 0x004C, 0x0049, 0x004E, 0x306E, 0x5185, 0x8A33
))
$wsDash.Cells.Item($stackTop, 1).Value2 = $stackTitle
$wsDash.Cells.Item($stackTop, 1).Font.Bold = $true
$st = $stackTop + 2
$wsDash.Cells.Item($st, 1).Value2 = $dhMonth
$wsDash.Cells.Item($st, 2).Value2 = 'Instagram'
$wsDash.Cells.Item($st, 3).Value2 = 'YouTube'
$wsDash.Cells.Item($st, 4).Value2 = 'stand.fm'
$wsDash.Cells.Item($st, 5).Value2 = 'note'
$wsDash.Range("A$st", "E$st").Font.Bold = $true

$rawName = SheetNameRaw
$wsDash.Cells.Item($st + 1, 1).Value2 = $M1
$wsDash.Cells.Item($st + 1, 2).Formula = "='$rawName'!C2"
$wsDash.Cells.Item($st + 1, 3).Formula = "='$rawName'!C3"
$wsDash.Cells.Item($st + 1, 4).Formula = "='$rawName'!C4"
$wsDash.Cells.Item($st + 1, 5).Formula = "='$rawName'!C5"
$wsDash.Cells.Item($st + 2, 1).Value2 = $M2
$wsDash.Cells.Item($st + 2, 2).Formula = "='$rawName'!C7"
$wsDash.Cells.Item($st + 2, 3).Formula = "='$rawName'!C8"
$wsDash.Cells.Item($st + 2, 4).Formula = "='$rawName'!C9"
$wsDash.Cells.Item($st + 2, 5).Formula = "='$rawName'!C10"
$wsDash.Cells.Item($st + 3, 1).Value2 = $M3
$wsDash.Cells.Item($st + 3, 2).Formula = "='$rawName'!C12"
$wsDash.Cells.Item($st + 3, 3).Formula = "='$rawName'!C13"
$wsDash.Cells.Item($st + 3, 4).Formula = "='$rawName'!C14"
$wsDash.Cells.Item($st + 3, 5).Formula = "='$rawName'!C15"

$evRow = $st + 6
$evTitle = (-join [char[]](0x30A4, 0x30D9, 0x30F3, 0x30C8, 0x004C, 0x0049, 0x004E, 0x4EBA, 0x6570, 0x5185, 0x8A33))
$wsDash.Cells.Item($evRow - 1, 1).Value2 = $evTitle
$wsDash.Cells.Item($evRow - 1, 1).Font.Bold = $true
$wsDash.Cells.Item($evRow, 1).Value2 = $dhMonth
$wsDash.Cells.Item($evRow, 2).Value2 = 'Instagram'
$wsDash.Cells.Item($evRow, 3).Value2 = 'YouTube'
$wsDash.Cells.Item($evRow, 4).Value2 = 'stand.fm'
$wsDash.Cells.Item($evRow, 5).Value2 = 'note'
$wsDash.Range("A$evRow", "E$evRow").Font.Bold = $true

$wsDash.Cells.Item($evRow + 1, 1).Value2 = $M1
$wsDash.Cells.Item($evRow + 1, 2).Formula = "='$rawName'!D2"
$wsDash.Cells.Item($evRow + 1, 3).Formula = "='$rawName'!D3"
$wsDash.Cells.Item($evRow + 1, 4).Formula = "='$rawName'!D4"
$wsDash.Cells.Item($evRow + 1, 5).Formula = "='$rawName'!D5"
$wsDash.Cells.Item($evRow + 2, 1).Value2 = $M2
$wsDash.Cells.Item($evRow + 2, 2).Formula = "='$rawName'!D7"
$wsDash.Cells.Item($evRow + 2, 3).Formula = "='$rawName'!D8"
$wsDash.Cells.Item($evRow + 2, 4).Formula = "='$rawName'!D9"
$wsDash.Cells.Item($evRow + 2, 5).Formula = "='$rawName'!D10"
$wsDash.Cells.Item($evRow + 3, 1).Value2 = $M3
$wsDash.Cells.Item($evRow + 3, 2).Formula = "='$rawName'!D12"
$wsDash.Cells.Item($evRow + 3, 3).Formula = "='$rawName'!D13"
$wsDash.Cells.Item($evRow + 3, 4).Formula = "='$rawName'!D14"
$wsDash.Cells.Item($evRow + 3, 5).Formula = "='$rawName'!D15"

$wsDash.Range("B$($st + 1):E$($st + 3)").NumberFormat = '0'
$wsDash.Range("B$($evRow + 1):E$($evRow + 3)").NumberFormat = '0'

# Meeting / individual reservations by source (column E on raw sheet)
$resTitleRow = $evRow + 5
$resRow = $evRow + 6
$resTitle = (-join [char[]](
  0x9762, 0x8AC7, 0x4E88, 0x7D04, 0xFF08, 0x500B, 0x5225, 0xFF09, 0x306E, 0x5A92, 0x4F53, 0x5225,
  0x0020, 0x2014, 0x0020, 0x30A4, 0x30D9, 0x30F3, 0x30C8, 0x004C, 0x0049, 0x004E, 0x7D4C, 0x7531, 0x306E, 0x500B, 0x5225, 0x3078, 0x306E, 0x6D41, 0x5165
))
$wsDash.Cells.Item($resTitleRow, 1).Value2 = $resTitle
$wsDash.Cells.Item($resTitleRow, 1).Font.Bold = $true
$wsDash.Cells.Item($resRow, 1).Value2 = $dhMonth
$wsDash.Cells.Item($resRow, 2).Value2 = 'Instagram'
$wsDash.Cells.Item($resRow, 3).Value2 = 'YouTube'
$wsDash.Cells.Item($resRow, 4).Value2 = 'stand.fm'
$wsDash.Cells.Item($resRow, 5).Value2 = 'note'
$wsDash.Range("A$resRow", "E$resRow").Font.Bold = $true

$wsDash.Cells.Item($resRow + 1, 1).Value2 = $M1
$wsDash.Cells.Item($resRow + 1, 2).Formula = "='$rawName'!E2"
$wsDash.Cells.Item($resRow + 1, 3).Formula = "='$rawName'!E3"
$wsDash.Cells.Item($resRow + 1, 4).Formula = "='$rawName'!E4"
$wsDash.Cells.Item($resRow + 1, 5).Formula = "='$rawName'!E5"
$wsDash.Cells.Item($resRow + 2, 1).Value2 = $M2
$wsDash.Cells.Item($resRow + 2, 2).Formula = "='$rawName'!E7"
$wsDash.Cells.Item($resRow + 2, 3).Formula = "='$rawName'!E8"
$wsDash.Cells.Item($resRow + 2, 4).Formula = "='$rawName'!E9"
$wsDash.Cells.Item($resRow + 2, 5).Formula = "='$rawName'!E10"
$wsDash.Cells.Item($resRow + 3, 1).Value2 = $M3
$wsDash.Cells.Item($resRow + 3, 2).Formula = "='$rawName'!E12"
$wsDash.Cells.Item($resRow + 3, 3).Formula = "='$rawName'!E13"
$wsDash.Cells.Item($resRow + 3, 4).Formula = "='$rawName'!E14"
$wsDash.Cells.Item($resRow + 3, 5).Formula = "='$rawName'!E15"

$wsDash.Range("B$($resRow + 1):E$($resRow + 3)").NumberFormat = '0'

$futureText = (-join [char[]](
  0x4ECA, 0x5F8C, 0x306E, 0x62E1, 0x5F35, 0xFF08, 0x904B, 0x7528, 0x304C, 0x5897, 0x3048, 0x305F, 0x3089, 0xFF09, 0x003A, 0x0020,
  0x30D4, 0x30DC, 0x30C3, 0x30C8, 0x30C6, 0x30FC, 0x30D6, 0x30EB, 0x5316, 0x3001, 0x6708, 0x6B21, 0x30B9, 0x30D1, 0x30FC, 0x30AF, 0x30E9, 0x30A4, 0x30F3, 0x3001,
  0x30B5, 0x30F3, 0x30AD, 0x30FC, 0x56F3, 0xFF08, 0x30A2, 0x30C9, 0x30AA, 0x30F3, 0x7B49, 0xFF09, 0x306F, 0x7B2C, 0x0032, 0x30D5, 0x30A7, 0x30FC, 0x30BA, 0x3067, 0x691C, 0x8A0E, 0x3002,
  0x7387, 0x306F, 0x5E38, 0x306B, 0x4EBA, 0x6570, 0xFF08, 0x5206, 0x5B50, 0x30FB, 0x5206, 0x6BCD, 0xFF09, 0x3068, 0x4F75, 0x8A18, 0x3002
))
$futureRow = $resRow + 6
$wsDash.Range("A$futureRow", "G$($futureRow + 1)").Merge() | Out-Null
$wsDash.Cells.Item($futureRow, 1).Value2 = $futureText
$wsDash.Cells.Item($futureRow, 1).WrapText = $true

$xlColumnClustered = 51
$xlLine = 4
$dataEnd = $dashHeaderRow + 3

$left1 = 400
$top1 = 10
$w = 380
$h = 240

$co1 = $wsDash.ChartObjects().Add($left1, $top1, $w, $h)
$ch1 = $co1.Chart
$ch1.ChartType = $xlColumnClustered
$rng1 = $wsDash.Range($wsDash.Cells.Item($dashHeaderRow, 1), $wsDash.Cells.Item($dataEnd, 4))
$ch1.SetSourceData($rng1)
$ch1.HasTitle = $true
$ch1.ChartTitle.Text = 'Monthly funnel counts (priority chart)'
$ch1.Legend.Position = -4152

$co2 = $wsDash.ChartObjects().Add($left1, $top1 + $h + 20, $w, $h)
$ch2 = $co2.Chart
$ch2.ChartType = $xlLine
$rng2 = $wsDash.Application.Union(
  $wsDash.Range($wsDash.Cells.Item($dashHeaderRow, 1), $wsDash.Cells.Item($dataEnd, 1)),
  $wsDash.Range($wsDash.Cells.Item($dashHeaderRow, 5), $wsDash.Cells.Item($dataEnd, 6))
)
$ch2.SetSourceData($rng2)
$ch2.HasTitle = $true
$ch2.ChartTitle.Text = 'Transition rates (see Event LINE count in table)'
$ch2.Legend.Position = -4152

$left2 = 30
$top2 = 320
$co3 = $wsDash.ChartObjects().Add($left2, $top2, $w, $h)
$ch3 = $co3.Chart
$ch3.ChartType = $xlColumnClustered
$rng3 = $wsDash.Range($wsDash.Cells.Item($st, 1), $wsDash.Cells.Item($st + 3, 5))
$ch3.SetSourceData($rng3)
$ch3.HasTitle = $true
$ch3.ChartTitle.Text = 'Normal LINE: per month, bars = IG / YT / stand / note'
$yInflow = (-join [char[]](0x6D41, 0x5165, 0x6570, 0xFF08, 0x4EBA, 0xFF09))
$ch3.Axes(2).HasTitle = $true
$ch3.Axes(2).AxisTitle.Text = $yInflow

$co4 = $wsDash.ChartObjects().Add($left2 + $w + 30, $top2, $w, $h)
$ch4 = $co4.Chart
$ch4.ChartType = $xlColumnClustered
$rng4 = $wsDash.Range($wsDash.Cells.Item($evRow, 1), $wsDash.Cells.Item($evRow + 3, 5))
$ch4.SetSourceData($rng4)
$ch4.HasTitle = $true
$ch4.ChartTitle.Text = 'Event LINE: per month, bars = IG / YT / stand / note'
$ch4.Axes(2).HasTitle = $true
$ch4.Axes(2).AxisTitle.Text = $yInflow

$top3 = $top2 + $h + 40
$co5 = $wsDash.ChartObjects().Add($left2, $top3, $w, $h)
$ch5 = $co5.Chart
$ch5.ChartType = $xlColumnClustered
$rng5 = $wsDash.Range($wsDash.Cells.Item($resRow, 1), $wsDash.Cells.Item($resRow + 3, 5))
$ch5.SetSourceData($rng5)
$ch5.HasTitle = $true
$ch5.ChartTitle.Text = 'Meeting bookings: per month, bars = IG / YT / stand / note'
$yBooking = (-join [char[]](0x4E88, 0x7D04, 0x6570, 0xFF08, 0x4EF6, 0xFF09))
$ch5.Axes(2).HasTitle = $true
$ch5.Axes(2).AxisTitle.Text = $yBooking

$wsDash.Range('A:G').EntireColumn.AutoFit() | Out-Null

if (Test-Path -LiteralPath $outPath) { Remove-Item -LiteralPath $outPath -Force }
$xlOpenXMLWorkbook = 51
$wb.SaveAs($outPath, $xlOpenXMLWorkbook)

$wb.Close($false)
$xl.Quit()

[System.Runtime.InteropServices.Marshal]::ReleaseComObject($ch5) | Out-Null
[System.Runtime.InteropServices.Marshal]::ReleaseComObject($co5) | Out-Null
[System.Runtime.InteropServices.Marshal]::ReleaseComObject($ch4) | Out-Null
[System.Runtime.InteropServices.Marshal]::ReleaseComObject($co4) | Out-Null
[System.Runtime.InteropServices.Marshal]::ReleaseComObject($ch3) | Out-Null
[System.Runtime.InteropServices.Marshal]::ReleaseComObject($co3) | Out-Null
[System.Runtime.InteropServices.Marshal]::ReleaseComObject($ch2) | Out-Null
[System.Runtime.InteropServices.Marshal]::ReleaseComObject($co2) | Out-Null
[System.Runtime.InteropServices.Marshal]::ReleaseComObject($ch1) | Out-Null
[System.Runtime.InteropServices.Marshal]::ReleaseComObject($co1) | Out-Null
[System.Runtime.InteropServices.Marshal]::ReleaseComObject($wsDash) | Out-Null
[System.Runtime.InteropServices.Marshal]::ReleaseComObject($wsRaw) | Out-Null
[System.Runtime.InteropServices.Marshal]::ReleaseComObject($wb) | Out-Null
[System.Runtime.InteropServices.Marshal]::ReleaseComObject($xl) | Out-Null
[GC]::Collect()
[GC]::WaitForPendingFinalizers()

Write-Host "Wrote $outPath"
Write-Host "Wrote $jsPath"
