// Auto-generated by build_dashboard.ps1 from funnel_raw.csv. Do not edit by hand.
window.FUNNEL_DATA = {
  labels: ["1月","2月","3月"],
  sources: ["Instagram","YouTube","stand.fm","note"],
  colors: ["#E91E63","#FF9800","#4CAF50","#2196F3"],
  normalLine: [[16,3,0,0],[11,1,1,2],[7,8,3,0]],
  eventLine: [[14,3,0,0],[6,0,1,1],[4,6,2,0]],
  meetings: [[1,0,0,0],[0,0,0,0],[0,1,0,0]]
};